### PR TITLE
Add Python 3 and PyPy support.

### PR DESCRIPTION
**Pull request by jamadden**
Drop deps on zope.app.zcmlfiles/testing/component (which was
circular).

Coverage is not quite 100% but is very close.

### CODE REVIEW

**Review by mgedmin — APPROVED** [review]
~~TL;DR~~ LGTM ;)

**Review by vangheem — APPROVED** [review]

**Comment by vangheem** [comment]
whoops, wrong tab. Ignore this :)

**Comment by jamadden** [comment]
Thanks! This one was pretty simple.

Could we get a PyPI release (or rights), please?

**Comment by mgedmin** [comment]
You have rights.

**Pull request merged**
